[[redirects]]
from = "/"
status = 200
to = "/index.html"

[[redirects]]
from = "/blog"
status = 200
to = "/index.html"

[[redirects]]
from = "/blog/*"
status = 200
to = "/index.html"

[[redirects]]
from = "/blog/:blogid"
status = 200
to = "/index.html"

[[redirects]]
from = "/product"
status = 200
to = "/index.html"

[[redirects]]
from = "/product/*"
status = 200
to = "/index.html"

[[redirects]]
from = "/product/:prodid"
status = 200
to = "/index.html"

[[redirects]]
from = "/product/productdetails/:id"
status = 200
to = "/index.html"

[[redirects]]
from = "/checkout"
status = 200
to = "/index.html"
